# Generated by Django 3.0.8 on 2020-07-25 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Todolist',
        ),
    ]
